# Revisar no funciona ..
version: "3.0"
services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    # networks:
    #   - laravel
  # pgsql:
  #   image: postgres:10-alpine #alpine
  #   restart: always
  #   container_name: pgsql
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE}
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - ./data/pgdata:/var/lib/postgresql/data
